from django.conf.urls import url
from . import views

app_name = 'assignments'

urlpatterns = [
    url(r'^assignments/$', views.AssignmentListView.as_view(), name='browse_assignments'),
    url(r'^assignment/detail/(?P<pk>[0-9]+)$', views.AssignmentDetailView.as_view(),
        name='assignment_detail'),
    url(r'^assignment/delete/(?P<pk>[0-9]+)$', views.AssignmentDelete.as_view(),
        name='assignment_delete'),
    url(r'^assignment/edit/(?P<pk>[0-9]+)$', views.AssignmentUpdate.as_view(),
        name='assignment_edit'),
    url(r'^assignment/create/$', views.AssignmentCreate.as_view(),
        name='assignment_create'),
    url(r'^texts/$', views.TextListView.as_view(), name='browse_texts'),
    url(r'^text/detail/(?P<pk>[0-9]+)$', views.TextDetailView.as_view(),
        name='text_detail'),
    url(r'^text/delete/(?P<pk>[0-9]+)$', views.TextDelete.as_view(),
        name='text_delete'),
    url(r'^text/edit/(?P<pk>[0-9]+)$', views.TextUpdate.as_view(),
        name='text_edit'),
    url(r'^text/create/$', views.TextCreate.as_view(),
        name='text_create'),
    url(r'^textversions/$', views.TextVersionListView.as_view(), name='browse_textversions'),
    url(r'^textversion/detail/(?P<pk>[0-9]+)$', views.TextVersionDetailView.as_view(),
        name='textversion_detail'),
    url(r'^textversion/delete/(?P<pk>[0-9]+)$', views.TextVersionDelete.as_view(),
        name='textversion_delete'),
    url(r'^textversion/edit/(?P<pk>[0-9]+)$', views.TextVersionUpdate.as_view(),
        name='textversion_edit'),
    url(r'^textversion/create/$', views.TextVersionCreate.as_view(),
        name='textversion_create'),
    url(r'^learners/$', views.LearnerListView.as_view(), name='browse_learners'),
    url(r'^learner/detail/(?P<pk>[0-9]+)$', views.LearnerDetailView.as_view(),
        name='learner_detail'),
    url(r'^learner/delete/(?P<pk>[0-9]+)$', views.LearnerDelete.as_view(),
        name='learner_delete'),
    url(r'^learner/edit/(?P<pk>[0-9]+)$', views.LearnerUpdate.as_view(),
        name='learner_edit'),
    url(r'^learner/create/$', views.LearnerCreate.as_view(),
        name='learner_create'),
    url(r'^learnerprofiles/$',
        views.LearnerProfileListView.as_view(), name='browse_learnerprofiles'
        ),
    url(r'^learnerprofile/detail/(?P<pk>[0-9]+)$', views.LearnerProfileDetailView.as_view(),
        name='learnerprofile_detail'),
    url(r'^learnerprofile/delete/(?P<pk>[0-9]+)$', views.LearnerProfileDelete.as_view(),
        name='learnerprofile_delete'),
    url(r'^learnerprofile/edit/(?P<pk>[0-9]+)$', views.LearnerProfileUpdate.as_view(),
        name='learnerprofile_edit'),
    url(r'^learnerprofile/create/$', views.LearnerProfileCreate.as_view(),
        name='learnerprofile_create'),
    url(r'^coursegroups/$',
        views.CourseGroupListView.as_view(), name='browse_coursegroups'
        ),
    url(r'^coursegroup/detail/(?P<pk>[0-9]+)$', views.CourseGroupDetailView.as_view(),
        name='coursegroup_detail'),
    url(r'^coursegroup/delete/(?P<pk>[0-9]+)$', views.CourseGroupDelete.as_view(),
        name='coursegroup_delete'),
    url(r'^coursegroup/edit/(?P<pk>[0-9]+)$', views.CourseGroupUpdate.as_view(),
        name='coursegroup_edit'),
    url(r'^coursegroup/create/$', views.CourseGroupCreate.as_view(),
        name='coursegroup_create'),
    url(r'^participants/$',
        views.ParticipantListView.as_view(), name='browse_participants'
        ),
    url(r'^participant/detail/(?P<pk>[0-9]+)$', views.ParticipantDetailView.as_view(),
        name='participant_detail'),
    url(r'^participant/delete/(?P<pk>[0-9]+)$', views.ParticipantDelete.as_view(),
        name='participant_delete'),
    url(r'^participant/edit/(?P<pk>[0-9]+)$', views.ParticipantUpdate.as_view(),
        name='participant_edit'),
    url(r'^participant/create/$', views.ParticipantCreate.as_view(),
        name='participant_create'),
]
